name: Deploy

on:
  schedule:
    - cron: 0 12 * * 1
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing packages
      run: |
        sudo apt update
        sudo apt install -y nasm gcc make binutils grub-pc-bin qemu-system-x86
        sudo apt install -y build-essential bison flex libgmp3-dev libmpc-dev
        sudo apt install -y xorriso mtools inkscape libmpfr-dev texinfo clang-format

    - name: Fetching submodules
      run: |
        git submodule update --init --recursive

    - name: Cache cross-toolchain
      uses: actions/cache@v2
      env:
        cache-name: cache-cross-toolchain
      with:
        path: |
          **/toolchain/local
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/toolchain/build-it.sh') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Building cross-toolchain
      run: |
        toolchain/build-it.sh

    - name: Building skiftOS
      run: |
          make all
          echo "::set-env name=RELEASE_TAG::$(date +'%y.%W')"

    - name: Creating Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.RELEASE_TAG  }}
        release_name: ${{ env.RELEASE_TAG }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Upload release assets
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/bootdisk.img
        asset_name: bootdisk.img
        asset_content_type: application/x-ima
